"""-

Revision ID: 77b67e75267b
Revises: caa4ca20c130
Create Date: 2025-12-15 11:21:18.077253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b67e75267b'
down_revision: Union[str, Sequence[str], None] = 'caa4ca20c130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deeplink_requests', sa.Column('is_registred', sa.Boolean(), nullable=False, comment='Регистрация на момент запроса'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deeplink_requests', 'is_registred')
    # ### end Alembic commands ###
