"""-

Revision ID: 7a6726d2cb72
Revises: 2ad094616ca7
Create Date: 2025-12-11 13:42:45.058368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a6726d2cb72'
down_revision: Union[str, Sequence[str], None] = '2ad094616ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deep_links', 'payload')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deep_links', sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Payload'))
    # ### end Alembic commands ###
