"""-

Revision ID: 00375246c19e
Revises: 6970ad8a65ea
Create Date: 2025-12-12 15:26:31.454862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00375246c19e'
down_revision: Union[str, Sequence[str], None] = '6970ad8a65ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deep_links', 'registration_steps')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deep_links', sa.Column('registration_steps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Шаги регистрации'))
    # ### end Alembic commands ###
