"""-

Revision ID: 6c12bf0f0df7
Revises: 180b1369397b
Create Date: 2025-09-12 17:26:45.288216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c12bf0f0df7'
down_revision: Union[str, Sequence[str], None] = '180b1369397b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'promocodes', ['value'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promocodes', type_='unique')
    # ### end Alembic commands ###
