"""-

Revision ID: 9f76bdb36ebd
Revises: 01f09f49f4ef
Create Date: 2025-11-06 10:01:54.616967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f76bdb36ebd'
down_revision: Union[str, Sequence[str], None] = '01f09f49f4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_black_list', sa.Column('name', sa.String(length=255), nullable=True, comment='Призвольное имя'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_black_list', 'name')
    # ### end Alembic commands ###
