"""-

Revision ID: 111da90a5656
Revises: dc4bca5f3317
Create Date: 2025-12-05 17:29:27.455144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '111da90a5656'
down_revision: Union[str, Sequence[str], None] = 'dc4bca5f3317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deep_links', 'link',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True,
               existing_comment='Ссылка')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deep_links', 'link',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False,
               existing_comment='Ссылка')
    # ### end Alembic commands ###
