"""-

Revision ID: caa4ca20c130
Revises: 00375246c19e
Create Date: 2025-12-12 15:27:50.175022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa4ca20c130'
down_revision: Union[str, Sequence[str], None] = '00375246c19e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deeplink_requests', sa.Column('registration_steps', sa.JSON(), nullable=True, comment='Шаги регистрации'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deeplink_requests', 'registration_steps')
    # ### end Alembic commands ###
