"""-

Revision ID: f9657541819b
Revises: 57f2850cf055
Create Date: 2025-09-11 12:44:56.812594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9657541819b'
down_revision: Union[str, Sequence[str], None] = '57f2850cf055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_posts', sa.Column('buttons_expiration', sa.DateTime(timezone=True), nullable=True, comment='Дата истечения срока действия кнопок'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_posts', 'buttons_expiration')
    # ### end Alembic commands ###
