"""-

Revision ID: 2ad094616ca7
Revises: a104af83bc37
Create Date: 2025-12-11 12:42:51.470202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad094616ca7'
down_revision: Union[str, Sequence[str], None] = 'a104af83bc37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deeplink_advertisements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Имя'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deeplink_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Имя'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deeplink_extras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Имя'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deeplink_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Имя'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deeplink_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Имя'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('deep_links', sa.Column('source_id', sa.Integer(), nullable=False))
    op.add_column('deep_links', sa.Column('campaign_id', sa.Integer(), nullable=False))
    op.add_column('deep_links', sa.Column('advertisement_id', sa.Integer(), nullable=False))
    op.add_column('deep_links', sa.Column('flow_id', sa.Integer(), nullable=False))
    op.add_column('deep_links', sa.Column('extra_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'deep_links', 'deeplink_flows', ['flow_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'deep_links', 'deeplink_extras', ['extra_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'deep_links', 'deeplink_campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'deep_links', 'deeplink_advertisements', ['advertisement_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'deep_links', 'deeplink_sources', ['source_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deep_links', type_='foreignkey')
    op.drop_constraint(None, 'deep_links', type_='foreignkey')
    op.drop_constraint(None, 'deep_links', type_='foreignkey')
    op.drop_constraint(None, 'deep_links', type_='foreignkey')
    op.drop_constraint(None, 'deep_links', type_='foreignkey')
    op.drop_column('deep_links', 'extra_id')
    op.drop_column('deep_links', 'flow_id')
    op.drop_column('deep_links', 'advertisement_id')
    op.drop_column('deep_links', 'campaign_id')
    op.drop_column('deep_links', 'source_id')
    op.drop_table('deeplink_sources')
    op.drop_table('deeplink_flows')
    op.drop_table('deeplink_extras')
    op.drop_table('deeplink_campaigns')
    op.drop_table('deeplink_advertisements')
    # ### end Alembic commands ###
