"""-

Revision ID: ffdaf182741a
Revises: 111da90a5656
Create Date: 2025-12-05 17:49:46.433571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffdaf182741a'
down_revision: Union[str, Sequence[str], None] = '111da90a5656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deep_links', sa.Column('comment', sa.String(length=1000), nullable=True, comment='Комментарий'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deep_links', 'comment')
    # ### end Alembic commands ###
