"""-

Revision ID: e78865a6c3c3
Revises: e8ce914115c1
Create Date: 2025-09-11 16:52:37.264363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e78865a6c3c3'
down_revision: Union[str, Sequence[str], None] = 'e8ce914115c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_posts', sa.Column('is_buttons_deleted', sa.Boolean(), nullable=True, comment='Флаг удаления кнопок'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_posts', 'is_buttons_deleted')
    # ### end Alembic commands ###
