"""-

Revision ID: c5ccb9e88127
Revises: 6c12bf0f0df7
Create Date: 2025-10-10 14:16:11.645228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ccb9e88127'
down_revision: Union[str, Sequence[str], None] = '6c12bf0f0df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_clients', sa.Column('city', sa.String(length=255), nullable=True, comment='Город'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_clients', 'city')
    # ### end Alembic commands ###
