"""-

Revision ID: a104af83bc37
Revises: 8e1ea2f18895
Create Date: 2025-12-08 13:36:50.194643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a104af83bc37'
down_revision: Union[str, Sequence[str], None] = '8e1ea2f18895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deeplink_requests', sa.Column('received_at', sa.DateTime(timezone=True), nullable=False, comment='Дата получения запроса'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deeplink_requests', 'received_at')
    # ### end Alembic commands ###
