"""-

Revision ID: 19e6716e5fb5
Revises: c5ccb9e88127
Create Date: 2025-11-05 15:12:44.692129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e6716e5fb5'
down_revision: Union[str, Sequence[str], None] = 'c5ccb9e88127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_black_list',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Europe/Moscow', now())"), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Europe/Moscow', now())"), nullable=False, comment='Дата обновления'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=True, comment='ID пользователя в Telegram'),
    sa.Column('tg_username', sa.String(length=255), nullable=True, comment='Имя пользователя в Telegram'),
    sa.Column('reason', sa.String(length=1000), nullable=True, comment='Причина добавления в черный список'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Добавлен в черный список?'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_black_list')
    # ### end Alembic commands ###
