"""-

Revision ID: 8e1ea2f18895
Revises: ffdaf182741a
Create Date: 2025-12-08 13:14:51.079966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1ea2f18895'
down_revision: Union[str, Sequence[str], None] = 'ffdaf182741a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deeplink_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Europe/Moscow', now())"), nullable=False, comment='Дата создания'),
    sa.Column('deeplink_id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False, comment='ID пользователя в Telegram'),
    sa.ForeignKeyConstraint(['deeplink_id'], ['deep_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deeplink_requests')
    # ### end Alembic commands ###
