"""-

Revision ID: 22dd5b1c61d5
Revises: e78865a6c3c3
Create Date: 2025-09-11 16:59:53.864476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22dd5b1c61d5'
down_revision: Union[str, Sequence[str], None] = 'e78865a6c3c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel_posts', 'is_buttons_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='Флаг удаления кнопок')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel_posts', 'is_buttons_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='Флаг удаления кнопок')
    # ### end Alembic commands ###
