"""-

Revision ID: 180b1369397b
Revises: 22dd5b1c61d5
Create Date: 2025-09-12 13:31:28.961380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180b1369397b'
down_revision: Union[str, Sequence[str], None] = '22dd5b1c61d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.Column('client_id', sa.Integer(), nullable=False, comment='Пользователь которуму присылается ссылки на бот и промокоды'),
    sa.Column('value', sa.String(length=255), nullable=False, comment='Промокод'),
    sa.Column('link', sa.String(length=255), nullable=False, comment='Ссылка на закрытый канал'),
    sa.Column('expire_date', sa.DateTime(), nullable=False, comment='Дата истечения промокода (ссылки на закрытый канал)'),
    sa.Column('subscriber_tg_id', sa.BigInteger(), nullable=True, comment='tg id пользователя который подписался на закрытый канал'),
    sa.Column('date_of_join', sa.DateTime(), nullable=True, comment='Дата присоеденения к закрытому каналу'),
    sa.ForeignKeyConstraint(['client_id'], ['tg_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promocodes')
    # ### end Alembic commands ###
