"""-

Revision ID: d6668046ecfb
Revises: 77b67e75267b
Create Date: 2025-12-15 11:46:07.562399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6668046ecfb'
down_revision: Union[str, Sequence[str], None] = '77b67e75267b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deeplink_requests', 'is_registred',
               existing_type=sa.BOOLEAN(),
               comment='Зарегистрирован?',
               existing_comment='Регистрация на момент запроса',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deeplink_requests', 'is_registred',
               existing_type=sa.BOOLEAN(),
               comment='Регистрация на момент запроса',
               existing_comment='Зарегистрирован?',
               existing_nullable=False)
    # ### end Alembic commands ###
