"""-

Revision ID: 6970ad8a65ea
Revises: 7a6726d2cb72
Create Date: 2025-12-12 14:45:28.711905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6970ad8a65ea'
down_revision: Union[str, Sequence[str], None] = '7a6726d2cb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deep_links', sa.Column('registration_steps', sa.JSON(), nullable=True, comment='Шаги регистрации'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deep_links', 'registration_steps')
    # ### end Alembic commands ###
