"""-

Revision ID: 57f2850cf055
Revises: 724edb4618fa
Create Date: 2025-09-09 16:48:41.774205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision: str = '57f2850cf055'
down_revision: Union[str, Sequence[str], None] = '724edb4618fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Europe/Moscow', now())"), nullable=False, comment='Дата создания'),
    sa.Column('caption', sa.String(length=1200), nullable=False, comment='Подпись под картинкой'),
    sa.Column('photo', sqlalchemy_file.types.ImageField(), nullable=True, comment='Фото'),
    sa.Column('chat_id', sa.String(length=255), nullable=True, comment='ID чата'),
    sa.Column('message_id', sa.BigInteger(), nullable=True, comment='ID сообщения'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_posts')
    # ### end Alembic commands ###
