"""-

Revision ID: dc4bca5f3317
Revises: 9f76bdb36ebd
Create Date: 2025-12-05 16:02:34.919787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc4bca5f3317'
down_revision: Union[str, Sequence[str], None] = '9f76bdb36ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deep_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Europe/Moscow', now())"), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Europe/Moscow', now())"), nullable=False, comment='Дата обновления'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Имя'),
    sa.Column('payload', sa.JSON(), nullable=False, comment='Payload'),
    sa.Column('link', sa.String(length=1000), nullable=False, comment='Ссылка'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deep_links')
    # ### end Alembic commands ###
