"""-

Revision ID: e8ce914115c1
Revises: 6ce27e89397d
Create Date: 2025-09-11 13:59:05.961563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8ce914115c1'
down_revision: Union[str, Sequence[str], None] = '6ce27e89397d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel_posts', 'buttons_expiration',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='Дата истечения срока действия кнопок',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel_posts', 'buttons_expiration',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='Дата истечения срока действия кнопок',
               existing_nullable=True)
    # ### end Alembic commands ###
