"""-

Revision ID: a8ff92417af3
Revises: d6668046ecfb
Create Date: 2026-02-18 10:48:45.725217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8ff92417af3'
down_revision: Union[str, Sequence[str], None] = 'd6668046ecfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deeplink_requests', sa.Column('invite_link', sa.String(length=1000), nullable=True, comment='Ссылка на приглашение в закрытый канал'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deeplink_requests', 'invite_link')
    # ### end Alembic commands ###
